# Shell and everyday command-line tools.
brew "atuin"
brew "autossh"
brew "bat"
brew "btop"
brew "chezmoi"
brew "coreutils"
brew "direnv"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gnupg"
brew "jq"
brew "lazygit"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "tmux"
brew "tree"
brew "wget"
brew "yazi"
brew "yq"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Language and build tooling used across projects.
brew "clang-format"
brew "cmake"
brew "go"
brew "maven"
brew "node"
brew "openjdk@11"
brew "openjdk@17"
brew "pnpm"
brew "python@3.12"
brew "uv"

# Developer applications.
cask "docker-desktop"
cask "font-hack-nerd-font"
cask "font-lilex-nerd-font"
cask "ghostty"
cask "iterm2"
cask "postman"
cask "visual-studio-code"
cask "zed"
